language: node_js
node_js:
- stable
cache:
  directories:
    - node_modules
env:
  global:
    secure: nQgRfEQyQhFzOAdw41qlquTqIvbxZgZWgRftaAzvM25+rturbLT0nEXsTQ7Hbqdilp1Ponqd9DcOfwtGfFcky76zHpoCwa2AMfkY1ryjJosGSStbHcHuVDT4MDdGpJUwrP2d7TWK9k24PMZWmHfAKIYpxYx7N9W7I/393owO4ZcefvAhVSOBBroMTtOFlBQyPoyrTDSUPIzpLjnmcTRqurDLnQKVaeQKTTUOiS0TQx3TnuNAdUw9yVU0Iey/us36a/6Rq7z2/3nomP0DgKqgi+/m7cLKHBkDfj9C5p+/z2NZvA8XazpRKA/cGY15kyLr0P0cPpbPKBK7eK05twH2UXos1QlPKgFr+sxjVlK8b1i+DnV2VB7syzE0tUijLKt/RL290XWmPFazDVQbFW8FGnmPko7siiH27M9EqqLoADF7zDwwRs/hEUa2d1dpJUq2cPEpOnh4OBMHAn4vGz0akuhfWe/MooicrO12XmDWLBBdCF28cuJ0GoZCXQL3dE7DDcq9UsOqJlqxNLQRxTdiPyG+laPZHVM1OcU4lRv2pGrW2jJrYGw7L3fS17ZxphcEOKOE/KnkuGyp/U8/2sML2ZOqILGjmpLL8M7qLydoZZscPoIeKB+J1veSn3UPkoaKeAEcedDoaZ+h4UgDajGErBHWOZuK1Ir+pZX9agTZTNk=
script: bash scripts/travis-deploy.sh
